# Generated by Django 2.2.17 on 2021-01-18 11:40

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=askcompany.utils.uuid_upload_to),
        ),
    ]
